project:
  type: website

website:
  title: "Download on Data"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - icon: play-btn
        href: talks.qmd
        text: "Speaking"
      - icon: github
        href: https://github.com/
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

